name: Build Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B package
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: Build
          path: target/GeyserConnect.jar
