name: Build Pull Request

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.idea/copyright/*.xml' 
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'bind9/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 21

      - name: Build GeyserConnect
        run: ./gradlew build

      - name: Archive artifacts
        # See https://github.com/actions/upload-artifact/commits
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: success()
        with:
          name: GeyserConnect
          path: build/libs/GeyserConnect.jar
          if-no-files-found: error
